### ISSUE TITLE
Generated config not writeable

### ISSUE THREAD

**Issue by jtojnar** [brailcom/speechd#649]
### Steps to reproduce
1. Delete the old `~/.config/speech-dispatcher`
2. Run `spd-conf` (default values are fine)

### Obtained behavior

The process will fail due to permission error:

```ShellSession
$ result/bin/spd-conf

Speech Dispatcher configuration tool

Do you want to setup a completely new configuration? [yes] :
>
Do you want to create/setup a 'user' or 'system' configuration? [user] :
>
User configuration created in /home/jtojnar/.config/speech-dispatcher
Configuring user settings for Speech Dispatcher
Default output module [espeak-ng] :
>
Default language (two/three-letter iso language code like "en" or "cs", possibly with a region qualification.) [en-US] :
>
Default audio output method [pulse] :
>
Default speech rate (on the scale of -100..100, 0 is default, 50 is faster, -50 is slower) [0] :
>
Default speech pitch (on the scale of -100..100, 0 is default, 50 is higher, -50 is lower) [0] :
>
Default speech pitch range (on the scale of -100..100, 0 is default, 50 is higher, -50 is lower) [0] :
>
Traceback (most recent call last):
  File "/nix/store/3qk9jcdhzg11nbf417kfh2kqwsf0n9yd-speech-dispatcher-0.11.0/bin/.spd-conf-wrapped", line 27, in <module>
    sys.exit(speechd_config.main())
  File "/nix/store/3qk9jcdhzg11nbf417kfh2kqwsf0n9yd-speech-dispatcher-0.11.0/lib/python3.9/site-packages/speechd_config/config.py", line 822, in main
    configure.complete_config()
  File "/nix/store/3qk9jcdhzg11nbf417kfh2kqwsf0n9yd-speech-dispatcher-0.11.0/lib/python3.9/site-packages/speechd_config/config.py", line 735, in complete_config
    self.configure_basic_settings(type='user')
  File "/nix/store/3qk9jcdhzg11nbf417kfh2kqwsf0n9yd-speech-dispatcher-0.11.0/lib/python3.9/site-packages/speechd_config/config.py", line 656, in configure_basic_settings
    self.options_substitute(configfile,
  File "/nix/store/3qk9jcdhzg11nbf417kfh2kqwsf0n9yd-speech-dispatcher-0.11.0/lib/python3.9/site-packages/speechd_config/config.py", line 542, in options_substitute
    for line in fileinput.input(configfile, inplace=True, backup=".bak"):
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/fileinput.py", line 249, in __next__
    line = self._readline()
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/fileinput.py", line 343, in _readline
    os.rename(self._filename, self._backupfilename)
PermissionError: [Errno 13] Permission denied: '/home/jtojnar/.config/speech-dispatcher/speechd.conf' -> '/home/jtojnar/.config/speech-dispatcher/speechd.conf.bak

$ ls -la /home/jtojnar/.config/speech-dispatcher/
dr-xr-xr-x   5 jtojnar users 4.0K Jan  1  1970 .
drwx------ 188 jtojnar users 4.0K Jan  8 17:27 ..
dr-xr-xr-x   2 jtojnar users 4.0K Jan  1  1970 clients
dr-xr-xr-x   2 jtojnar users 4.0K Jan  1  1970 desktop
dr-xr-xr-x   2 jtojnar users 4.0K Jan  1  1970 modules
-r--r--r--   1 jtojnar users  14K Jan  1  1970 speechd.conf
```

### Expected behavior

It should succeed and the configs should be owner-writeable.

### Behavior information

Please follow the next step, to provide us with precious information about how things went wrong on your machine:

### Distribution
NixOS

### Version of Speech-dispatcher
0.11.0

**Comment by jtojnar** [comment]
Hmm, that is probably because the file is copied from `/nix/store` installation location which is immutable.

**Comment by sthibaul** [comment]
Possibly a chmod is needed there, yes
