### ISSUE TITLE
Double free in escape_dot

### ISSUE THREAD

**Issue by Jookia** [brailcom/speechd#741]
Sorry for the poor bug report, the only information I have is a core dump without symbols and source code.

Backtrace:

```
#0  0x00007fa7f42e434c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#1  0x00007fa7f42974b8 in raise () from /usr/lib/libc.so.6
#2  0x00007fa7f4281534 in abort () from /usr/lib/libc.so.6
#3  0x00007fa7f42d8397 in __libc_message () from /usr/lib/libc.so.6
#4  0x00007fa7f42ee33c in malloc_printerr () from /usr/lib/libc.so.6
#5  0x00007fa7f42f0420 in _int_free () from /usr/lib/libc.so.6
#6  0x00007fa7f42f2be3 in free () from /usr/lib/libc.so.6
#7  0x000055a610fe30e2 in output_speak ()
#8  0x000055a610fdf1c1 in speak ()
#9  0x00007fa7f42e25c2 in start_thread () from /usr/lib/libc.so.6
#10 0x00007fa7f4367584 in clone () from /usr/lib/libc.so.6
(gdb) x/s *(char**)$rbx
0x7fa7ebfff640:	"@\366\377\353\247\177"
(gdb) frame 7
#7  0x000055a610fe30e2 in output_speak ()
(gdb) x/s *(char**)($rbx+0x10)
0x7fa7e40b4610:	"\360\361\003\344\247\177"
```

output_speak is failing around here:

```
   0x000055a610fe30d7 <+87>:	cmp    %rax,%rdi
   0x000055a610fe30da <+90>:	je     0x55a610fe30e6 <output_speak+102>
   0x000055a610fe30dc <+92>:	call   *0x137ce(%rip)        # 0x55a610ff68b0
=> 0x000055a610fe30e2 <+98>:	mov    %r13,0x10(%rbx)
   0x000055a610fe30e6 <+102>:	mov    0x60(%r12),%rax
   0x000055a610fe30eb <+107>:	movl   $0xffffffff,0x18(%rbx)
```

Which is equivalent to:

```
        newbuf = escape_dot(msg->buf);
        if (newbuf != msg->buf) {
=>                g_free(msg->buf);
                msg->buf = newbuf;
        }
        msg->bytes = -1;
```

escape_dot has already freed the buffer:

```
        } else {
                g_string_append(ntext, otext);
                g_free(ootext);
                ret = ntext->str;
                g_string_free(ntext, 0);
        }
```

_int_free hangs around here:

```
   0x00007fa7f42f0414 <+1972>:	lea    0x127db5(%rip),%rdi        # 0x7fa7f44181d0
   0x00007fa7f42f041b <+1979>:	call   0x7fa7f42ee320 <malloc_printerr>
=> 0x00007fa7f42f0420 <+1984>:	lea    0x127dc9(%rip),%rdi        # 0x7fa7f44181f0
   0x00007fa7f42f0427 <+1991>:	call   0x7fa7f42ee320 <malloc_printerr>
```

That gives us:

```
(gdb) x/s 0x7fa7f44181d0             
0x7fa7f44181d0:	"double free or corruption (out)"
```

So looks like there's a double free happening here.

**Comment by sthibaul** [comment]
> Sorry for the poor bug report

It contained everything needed to understand the issue!
Thanks!
